version: '3'
services:
  hedgedoc_database:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hedgedoc
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - internal
      - traefik-public
    restart: always
  hedgedoc:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:1.10.0
    environment:
      - CMD_DB_URL=postgres://hedgedoc:password@hedgedoc_database:5432/hedgedoc
      - CMD_DOMAIN=hedgedoc.selfhostyour.tech
      - CMD_PROTOCOL_USESSL=true
      - CMD_URL_ADDPORT=false
      - CMD_SESSION_SECRET=change_this_to_a_long_random_string
      - CMD_CSP_ENABLE=true
      - CMD_HELMET_ENABLE=true
    volumes:
      - uploads:/hedgedoc/public/uploads
    networks:
      - internal
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.hedgedoc.rule=Host(`hedgedoc.selfhostyour.tech`)
      - traefik.http.routers.hedgedoc.entrypoints=web
      - traefik.http.routers.hedgedoc.middlewares=redirect-to-https
      - traefik.http.routers.hedgedoc-secure.rule=Host(`hedgedoc.selfhostyour.tech`)
      - traefik.http.routers.hedgedoc-secure.entrypoints=websecure
      - traefik.http.routers.hedgedoc-secure.tls=true
      - traefik.http.routers.hedgedoc-secure.tls.certresolver=letsencrypt
      - traefik.http.services.hedgedoc.loadbalancer.server.port=3000
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
    restart: always
    depends_on:
      - hedgedoc_database
volumes:
  database:
  uploads:
networks:
  internal:
  traefik-public:
    external: true