services:
  baserow:
    image: baserow/baserow:1.30.1
    environment:
      BASEROW_PUBLIC_URL: 'https://baserow.selfhostyour.tech'
    ports:
      - 80:80
      - 443:443
    env_file: ./.env
    networks:
      - internal
      - traefik-public
    volumes:
      - ./data/baserow:/baserow/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.baserow.rule=Host(`${BASEROW_DOMAIN}`)
      - traefik.http.routers.baserow.entrypoints=https
      - traefik.http.routers.baserow.tls=true
      - traefik.http.routers.baserow.tls.certresolver=le
      - traefik.http.services.baserow.loadbalancer.server.port=80
      - traefik.http.services.baserow.loadbalancer.passHostHeader=true
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true