version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    deploy:
      placement:
        constraints:
          - node.hostname == grapefruit
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.n8n.rule=Host(`n8n.monadical.io`)
        - traefik.http.routers.n8n.tls=true
        - traefik.http.routers.n8n.entrypoints=https
        - traefik.http.routers.n8n.tls.certresolver=le
        - traefik.http.routers.n8n-http.rule=Host(`n8n.monadical.io`)
        - traefik.http.routers.n8n-http.middlewares=https-redirect
        - traefik.http.routers.n8n-http.entrypoints=http
        - traefik.http.services.n8n.loadbalancer.server.port=5678
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.middlewares.n8n.headers.SSLRedirect=true
        - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
        - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
        - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
        - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
        - traefik.http.middlewares.n8n.headers.SSLHost=monadical.io
        - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
        - traefik.http.middlewares.n8n.headers.STSPreload=true
        # - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
      - N8N_HOST=n8n.monadical.io
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.monadical.io
      - GENERIC_TIMEZONE=America/Montreal
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - net
      - traefik-public

volumes:
  n8n_data:

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
